### ISSUE TITLE
Hazard detection/forwarding, stalling unit

### ISSUE THREAD

**Issue by AhsanAliUet** [hamza-akhtar-dev/Pak-RV-Core#9]
Hazard detection unit is missing. We need to add that in our core so that all the assembly codes are written without any hesitation.

In that unit, we need to solve hazards by `forwarding and stalling`.

**Comment by hamza-akhtar-dev** [comment]
Hazarding detection unit and forwarding unit is added in the RTL. Also fixed some bugs regarding hazards..

**Comment by hamza-akhtar-dev** [comment]
Hazarding detection unit and forwarding unit is added in the RTL. Also fixed some bugs regarding hazards.
